{
 "title": "mydashboard 000",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Dashboards",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT dashboard_id FROM dashboard_tag LIMIT 50 "
    }
   ]
  },
  {
   "title": "Dashboard List",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT name FROM dashboard_snapshot  LIMIT 50 "
    }
   ]
  },
  {
   "title": "Last Execution",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT last_execution FROM server_lock LIMIT 50 "
    }
   ]
  },
  {
   "title": "Failure Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(cache_key) FROM cache_data LIMIT 50 "
    }
   ]
  },
  {
   "title": "Migration Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT migration_id AS \"Migration ID\", sql AS \"SQL Query\", success \"Status\" FROM migration_log LIMIT 50 "
    }
   ]
  },
  {
   "title": "Our Team",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT name AS \"Name\", email AS \"Email\", company AS \"Company Name\", is_admin AS \"Is Admin\", email_verified AS \"Verified\", last_seen_at AS \"Last Active\" FROM \"user\" LIMIT 50 "
    }
   ]
  }
 ]
}